name: Terraform Plan
on:
  workflow_dispatch:
    types: 
    inputs:
      service:
        type: choice
        description: Kubernetes service to provision
        options:
          - eks
env:
  AWS_REGION : "ap-southeast-1"
permissions:
      id-token: write 
      contents: read
jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq
      
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
          
      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: "arn:aws:iam::020612890700:role/gha_oidc_assume_role"
          role-session-name: terraform_plan_session
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true
        
      - name: Terraform Init
        id: init
        run: |
          cd "${{ github.event.inputs.service }}" 
          terraform init

        
      - name: Terraform Plan
        id: plan
        run: |
          cd "${{ github.event.inputs.service }}"
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          terraform plan -no-color >> $GITHUB_STEP_SUMMARY